version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: h-dockurr-macos_app_1
      APP_PORT: 8008
      PROXY_AUTH_ADD: "false"

  app:
    image: dockurr/macos
    restart: on-failure
    environment:
      VERSION: "15"
      RAM_SIZE: "8G"
      CPU_CORES: "6"
      DISK_SIZE: "64G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - ${APP_DATA_DIR}/data:/storage:rw
    ports:
      - 8006:8008
      - 5900:5900/tcp
      - 5900:5900/udp
    stop_grace_period: 2m
